# Generated by Django 6.0.3 on 2026-03-30 10:25

from django.db import migrations


def populate_services(apps, schema_editor):
    Service = apps.get_model("core", "Service")
    services = [
        {
            "title": "Études et conception de sites techniques",
            "slug": "etudes-techniques",
            "description": "Des études personnalisées pour la conception et l'installation de sites techniques répondant aux normes industrielles.",
            "icon": "bi-diagram-3",
            "details": "Chez SETES SARL, nous réalisons des études techniques approfondies pour concevoir des infrastructures adaptées aux besoins spécifiques de chaque client. Nos équipes d'ingénieurs et de techniciens expérimentés effectuent une analyse complète des paramètres techniques, environnementaux et économiques avant de concevoir un projet. Grâce à notre expertise, nous assurons une optimisation des performances tout en respectant les normes les plus strictes de l'industrie. Nos solutions couvrent la conception de réseaux, la planification d'installations techniques, ainsi que l'ingénierie des systèmes complexes.",
            "image": "assets/img/services/etudes-techniques.webp",
            "order": 1,
        },
        {
            "title": "Fourniture et pose de systèmes solaires photovoltaïques",
            "slug": "systemes-solaires",
            "description": "Des solutions d'énergie renouvelable pour vos besoins en électricité durable et économique.",
            "icon": "bi-sun",
            "details": "Nous proposons des systèmes solaires photovoltaïques qui répondent aux besoins énergétiques des entreprises et des particuliers. Nos solutions incluent l'étude de faisabilité, la fourniture des équipements de haute qualité, l'installation sur site et la maintenance continue. Nous offrons une expertise complète allant de l'intégration des panneaux solaires à la gestion des batteries et des onduleurs, garantissant ainsi une production d'énergie propre et stable. En choisissant SETES SARL, vous optez pour une autonomie énergétique et une réduction significative de votre empreinte carbone.",
            "image": "assets/img/services/systemes-solaires.jpg",
            "order": 2,
        },
        {
            "title": "Fourniture et installation de systèmes de sécurité",
            "slug": "systemes-securite",
            "description": "Sécurisez vos installations avec nos systèmes de surveillance et de protection incendie.",
            "icon": "bi-shield-lock",
            "details": "Nous offrons des solutions de sécurité intégrées comprenant des systèmes de surveillance par caméras, des dispositifs de détection d'incendie, des contrôles d'accès sécurisés, et bien plus encore. Chaque système est conçu pour s'adapter à vos besoins spécifiques, que ce soit pour une entreprise, une industrie ou un espace résidentiel. Nos solutions incluent la fourniture, l'installation et la configuration des équipements, ainsi que la formation pour une utilisation optimale. Nous assurons également la maintenance préventive et corrective afin de garantir une protection continue.",
            "image": "assets/img/services/systemes-securite.webp",
            "order": 3,
        },
        {
            "title": "Maintenance et exploitation des systèmes télécoms",
            "slug": "maintenance-telecoms",
            "description": "Nous assurons l'audit, la maintenance et l'exploitation des systèmes FH, VSAT, FO et autres infrastructures télécom.",
            "icon": "bi-wifi",
            "details": "Nos services de maintenance télécom comprennent l'audit des infrastructures, la maintenance préventive et corrective, ainsi que l'exploitation continue des systèmes télécoms. Nous intervenons sur des technologies telles que les faisceaux hertziens (FH), les systèmes VSAT, la fibre optique (FO) et d'autres équipements critiques. Notre expertise garantit la disponibilité et la performance optimales de vos réseaux télécoms, réduisant ainsi les interruptions de service. Nous offrons des solutions sur-mesure, que ce soit pour des opérateurs télécoms, des institutions gouvernementales ou des entreprises privées.",
            "image": "assets/img/services/maintenance-telecoms.jpg",
            "order": 4,
        },
        {
            "title": "Fourniture de groupes électrogènes",
            "slug": "groupes-electrogenes",
            "description": "Nous proposons des solutions fiables pour assurer la continuité de l'alimentation électrique.",
            "icon": "bi-lightning",
            "details": "Nos solutions de fourniture de groupes électrogènes incluent la vente, l'installation et la maintenance d'équipements de différentes puissances adaptés à vos besoins spécifiques. Que ce soit pour une alimentation de secours, pour des sites industriels ou pour des installations temporaires, nous vous fournissons des générateurs robustes et fiables. Nos équipes d'experts vous accompagnent dans le choix des équipements, en assurant une configuration optimale pour garantir une disponibilité continue de l'énergie. Nos services incluent également la gestion de l'entretien préventif et des réparations pour prolonger la durée de vie des équipements.",
            "image": "assets/img/services/groupes-electrogenes.webp",
            "order": 5,
        },
        {
            "title": "Audit et maintenance des pylônes",
            "slug": "audit-pylones",
            "description": "Nos services incluent l'audit, l'installation et la maintenance des pylônes télécoms pour une performance optimale.",
            "icon": "bi-tower",
            "details": "Nous offrons des services complets pour l'audit, l'installation et la maintenance des pylônes de communication. Nos experts réalisent des inspections approfondies pour évaluer l'intégrité structurelle et la conformité des pylônes aux normes de sécurité. Nos services incluent également la modernisation des infrastructures existantes, l'installation de nouveaux pylônes et la gestion des systèmes de fixation d'équipements télécoms. Grâce à notre expertise, nous garantissons une performance optimale et une sécurité accrue de vos installations télécoms.",
            "image": "assets/img/services/audit-pylones.webp",
            "order": 6,
        },
        {
            "title": "Développement de solutions numériques",
            "slug": "solutions-numeriques",
            "description": "Ingénierie logicielle pour la gestion de l'énergie, l'analyse de données, la gestion des réseaux intelligents, et plus encore.",
            "icon": "bi-laptop",
            "details": "SETES SARL se positionne en tant qu'acteur clé dans le développement de solutions numériques sur-mesure. Nos services incluent la conception de logiciels de gestion de l'énergie, des systèmes de contrôle de la production d'énergies renouvelables, ainsi que des plateformes pour la gestion de réseaux intelligents. Nous offrons des solutions évolutives et performantes adaptées aux besoins spécifiques de chaque client. Notre expertise couvre également l'analyse de données, la prévision de consommation énergétique, et l'intégration de systèmes IoT pour une optimisation continue.",
            "image": "assets/img/services/solutions-numeriques.webp",
            "order": 7,
        },
    ]
    for s in services:
        Service.objects.get_or_create(slug=s["slug"], defaults=s)


def populate_testimonials(apps, schema_editor):
    Testimonial = apps.get_model("core", "Testimonial")
    testimonials = [
        {
            "company_name": "Alpha Technologies",
            "person_title": "Directeur Général",
            "content": "SETES SARL a été un partenaire fiable pour nos besoins en systèmes de sécurité et de maintenance. Leur expertise et leur professionnalisme ont été déterminants dans la réussite de notre projet.",
            "rating": 5,
            "order": 1,
        },
        {
            "company_name": "Global Energy Solutions",
            "person_title": "Responsable des Opérations",
            "content": "Nous avons confié à SETES SARL la fourniture et l'installation de nos systèmes solaires photovoltaïques. Leurs solutions ont parfaitement répondu à nos exigences de qualité et d'efficacité.",
            "rating": 5,
            "order": 2,
        },
        {
            "company_name": "TechnoComm",
            "person_title": "Chef de Projet",
            "content": "Grâce à l'expertise de SETES SARL, nous avons pu moderniser nos infrastructures télécoms avec des solutions innovantes et performantes. Leur équipe a su répondre à toutes nos attentes.",
            "rating": 5,
            "order": 3,
        },
        {
            "company_name": "SecureTech",
            "person_title": "Directeur de la Sécurité",
            "content": "SETES SARL nous a fourni des systèmes de surveillance et de protection incendie de haute qualité. Leur service après-vente est impeccable et toujours disponible.",
            "rating": 5,
            "order": 4,
        },
        {
            "company_name": "DataConnect",
            "person_title": "Ingénieur Réseaux",
            "content": "SETES SARL a joué un rôle clé dans l'optimisation de nos réseaux télécoms avec leur expertise en maintenance et audit. Nous sommes ravis des résultats obtenus.",
            "rating": 5,
            "order": 5,
        },
        {
            "company_name": "SoftInTech",
            "person_title": "Directeur Technique",
            "content": "Le développement de solutions numériques par SETES SARL a grandement contribué à la modernisation de nos systèmes de gestion. Leur approche innovante nous a permis de gagner en efficacité.",
            "rating": 5,
            "order": 6,
        },
    ]
    for t in testimonials:
        Testimonial.objects.get_or_create(company_name=t["company_name"], defaults=t)


def populate_team(apps, schema_editor):
    TeamMember = apps.get_model("core", "TeamMember")
    members = [
        {
            "name": "M HIMAN",
            "role": "Directeur Général",
            "photo": "assets/img/team/team-1.jpg",
            "order": 1,
        },
        {
            "name": "Mahamane Mourtala Haladou",
            "role": "Responsable des Opérations",
            "photo": "assets/img/team/team-5.jpg",
            "order": 2,
        },
        {
            "name": "Ibrahim Amini",
            "role": "Directeur Technique",
            "photo": "assets/img/team/team-6.jpg",
            "order": 3,
        },
        {
            "name": "Aïcha Sidibé",
            "role": "Responsable Administratif et Financier",
            "photo": "assets/img/team/team-4.jpg",
            "order": 4,
        },
        {
            "name": "ISSAKA HAMA Barhamou",
            "role": "Génie Logiciel",
            "photo": "assets/img/team/team-issaka.jpg",
            "order": 5,
        },
    ]
    for m in members:
        TeamMember.objects.get_or_create(name=m["name"], defaults=m)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_services, migrations.RunPython.noop),
        migrations.RunPython(populate_testimonials, migrations.RunPython.noop),
        migrations.RunPython(populate_team, migrations.RunPython.noop),
    ]
