# Generated by Django 6.0.3 on 2026-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_populate_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="legacy_image",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="teammember",
            name="legacy_photo",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, upload_to="services/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(blank=True, upload_to="team/"),
        ),
    ]
